version: "3"
services:
  back-end:
    build: ./Source/server
    container_name: "back-end"

  front-end:
    build: ./Source/client
    container_name: "front-end"
    depends_on:
      - back-end
  proxy:
    build: ./nginx
    container_name: "proxy"
    restart: always
    ports:
      - "80:80"
